// illusion_image_automation.js
// Complete pipeline for 400 unique illusion image generations with auto CTA overlay for Gemini/MidJourney automation

let generationIndex = 0,
    delay = 30000,
    totalGenerations = 400,
    retryDelay = 5000;

const illusions = [
    "a vineyard with vines forming a lyre ridge",
    "a mountain with peaks shaping a griffin ridge",
    "a harbor with boats forming a fleet ridge",
    "a forest with shadows creating a bear cub ridge",
    "a city with neon forming a heartbeat ridge",
    "a wheat field with stalks shaping a windmill ridge",
    "a coral reef with corals forming a palace ridge",
    "a desert with sand shaping a nomad ridge",
    "a library with books creating a tower ridge",
    "a carnival with tents forming a big top ridge",
    "a river with currents shaping a whirlpool ridge",
    "a skyline with cranes forming a skyline ridge",
    "a glacier with ice shaping a seal pup ridge",
    "a bamboo forest with stalks forming a pagoda ridge",
    "a labyrinth with turns creating a spiral galaxy ridge",
    "a coral reef with waves forming a trident ridge",
    "a night sky with stars shaping a nebula ridge",
    "a bridge with cables forming a web ridge",
    "a rose garden with blooms shaping a scepter ridge",
    "a city with lights forming a symphony ridge",
    "a chessboard with tiles creating a maze ridge",
    "a frozen lake with ice shaping a snow owl ridge",
    "a festival with fireworks forming a starburst ridge",
    "a desert with dunes creating a caravan trail ridge",
    "a waterfall with mist forming a phantom ridge",
    "a park with trees shaping a silhouette ridge",
    "a constellation with stars forming a harp ridge",
    "a train with cars creating a chain ridge",
    "a vineyard with rows forming a scroll ridge",
    "a mountain with cliffs shaping a condor ridge",
    "a harbor with docks forming a compass ridge",
    "a forest with vines creating a panther ridge",
    "a city with billboards shaping a marquee ridge",
    "a wheat field with paths forming a tractor ridge",
    "a coral reef with shells creating a spiral ridge",
    "a desert with mirages forming a mirage city ridge",
    "a library with windows shaping a book ridge",
    "a carnival with flags forming a trapeze ridge",
    "a river with rocks creating a canoe ridge",
    "a skyline with antennas forming a signal ridge",
    "a glacier with ridges shaping a narwhal ridge",
    "a bamboo forest with leaves forming a fan ridge",
    "a labyrinth with paths shaping a keyhole ridge",
    "a coral reef with anemones forming a jellyfish ridge",
    "a night sky with meteors creating a shooting star ridge",
    "a bridge with supports forming a crane ridge",
    "a rose garden with arches shaping a throne ridge",
    "a city with streetlights forming a melody ridge",
    "a chessboard with squares creating a shield ridge",
    "a frozen lake with patterns forming a snowflake ridge",
    "a festival with crowds shaping a stage ridge",
    "a desert with sand forming an hourglass ridge",
    "a waterfall with rainbows creating a prism ridge",
    "a park with shadows forming a carousel ridge",
    "a constellation with lines shaping a chariot ridge",
    "a train with tracks forming a tunnel ridge",
    "a vineyard with grapes creating a chalice ridge",
    "a mountain with snow shaping a yeti ridge",
    "a harbor with buoys forming a compass rose ridge",
    "a forest with leaves creating a stag ridge",
    "a city with bridges shaping a violin ridge",
    "a wheat field with rows forming a plow ridge",
    "a coral reef with fish schools creating a heart ridge",
    "a desert with winds shaping a dervish ridge",
    "a library with book spines forming a globe ridge",
    "a carnival with balloons creating a clown ridge",
    "a river with bends shaping a delta ridge",
    "a skyline with windows forming a code ridge",
    "a glacier with ice creating a walrus ridge",
    "a bamboo forest with shadows forming a koi ridge",
    "a labyrinth with paths creating a key ridge",
    "a coral reef with algae shaping a crown ridge",
    "a night sky with auroras forming a veil ridge",
    "a bridge with reflections creating a mirror ridge",
    "a rose garden with thorns shaping a dagger ridge",
    "a city with rooftops forming a skyline ridge",
    "a chessboard with moves creating a dance ridge",
    "a frozen lake with ice forming a crystal ridge",
    "a festival with lights shaping a sparkler ridge",
    "a desert with rocks forming a monument ridge",
    "a waterfall with mist creating a sprite ridge",
    "a park with trees forming a canopy ridge",
    "a constellation with stars shaping an arrow ridge",
    "a train with steam forming a whistle ridge",
    "a vineyard with leaves creating a wreath ridge",
    "a mountain with ridges forming a falcon ridge",
    "a harbor with waves shaping a siren ridge",
    "a forest with branches forming a lynx ridge",
    "a city with signs creating a billboard ridge",
    "a wheat field with wind shaping a scarecrow ridge",
    "a coral reef with colors forming a palette ridge",
    "a desert with dunes creating a crescent ridge",
    "a library with shelves shaping a ladder ridge",
    "a carnival with rides forming a rollercoaster ridge",
    "a river with ripples creating a mandala ridge",
    "a skyline with lights forming a constellation ridge",
    "a glacier with shadows shaping an iceberg ridge",
    "a bamboo forest with leaves forming a dragonfly ridge",
    "a labyrinth with walls creating a puzzle ridge",
    "a coral reef with fish forming a mosaic ridge",
    "a night sky with stars shaping a galaxy ridge",
    "a bridge with arches forming a rainbow ridge",
    "a rose garden with petals creating a fan ridge",
    "a city with streets forming a circuit ridge",
    "a chessboard with pieces shaping a fortress ridge",
    "a frozen lake with cracks forming a web ridge",
    "a festival with flags creating a parade ridge",
    "a desert with shadows forming a mirage ridge",
    "a waterfall with spray shaping a veil ridge",
    "a park with paths forming a labyrinth ridge",
    "a constellation with stars creating a crown ridge",
    "a train with tracks shaping a horizon ridge",
    "a vineyard with vines forming a lyre ridge",
    "a mountain with peaks shaping a griffin ridge",
    "a harbor with boats forming a fleet ridge",
    "a forest with shadows creating a bear cub ridge",
    "a city with neon forming a heartbeat ridge",
    "a wheat field with stalks shaping a windmill ridge",
    "a coral reef with corals forming a palace ridge",
    "a desert with sand shaping a nomad ridge",
    "a library with books creating a tower ridge",
    "a carnival with tents forming a big top ridge",
    "a river with currents shaping a whirlpool ridge",
    "a skyline with cranes forming a skyline ridge",
    "a glacier with ice shaping a seal pup ridge",
    "a bamboo forest with stalks forming a pagoda ridge",
    "a labyrinth with turns creating a spiral galaxy ridge",
    "a coral reef with waves forming a trident ridge",
    "a night sky with stars shaping a nebula ridge",
    "a bridge with cables forming a web ridge",
    "a rose garden with blooms shaping a scepter ridge",
    "a city with lights forming a symphony ridge",
    "a chessboard with tiles creating a maze ridge",
    "a frozen lake with ice shaping a snow owl ridge",
    "a festival with fireworks forming a starburst ridge",
    "a desert with dunes creating a caravan trail ridge",
    "a waterfall with mist forming a phantom ridge",
    "a park with trees shaping a silhouette ridge",
    "a constellation with stars forming a harp ridge",
    "a train with cars creating a chain ridge",
    "a vineyard with rows forming a scroll ridge",
    "a mountain with cliffs shaping a condor ridge",
    "a harbor with docks forming a compass ridge",
    "a forest with vines creating a panther ridge",
    "a city with billboards shaping a marquee ridge",
    "a wheat field with paths forming a tractor ridge",
    "a coral reef with shells creating a spiral ridge",
    "a desert with mirages forming a mirage city ridge",
    "a library with windows shaping a book ridge",
    "a carnival with flags forming a trapeze ridge",
    "a river with rocks creating a canoe ridge",
    "a skyline with antennas forming a signal ridge",
    "a glacier with ridges shaping a narwhal ridge",
    "a bamboo forest with leaves forming a fan ridge",
    "a labyrinth with paths shaping a keyhole ridge",
    "a coral reef with anemones forming a jellyfish ridge",
    "a night sky with meteors creating a shooting star ridge",
    "a bridge with supports forming a crane ridge",
    "a rose garden with arches shaping a throne ridge",
    "a city with streetlights forming a melody ridge",
    "a chessboard with squares creating a shield ridge",
    "a frozen lake with patterns forming a snowflake ridge",
    "a festival with crowds shaping a stage ridge",
    "a desert with sand forming an hourglass ridge",
    "a waterfall with rainbows creating a prism ridge",
    "a park with shadows forming a carousel ridge",
    "a constellation with lines shaping a chariot ridge",
    "a train with tracks forming a tunnel ridge",
    "a vineyard with grapes creating a chalice ridge",
    "a mountain with snow shaping a yeti ridge",
    "a harbor with buoys forming a compass rose ridge",
    "a forest with leaves creating a stag ridge",
    "a city with bridges shaping a violin ridge",
    "a wheat field with rows forming a plow ridge",
    "a coral reef with fish schools creating a heart ridge",
    "a desert with winds shaping a dervish ridge",
    "a library with book spines forming a globe ridge",
    "a carnival with balloons creating a clown ridge",
    "a river with bends shaping a delta ridge",
    "a skyline with windows forming a code ridge",
    "a glacier with ice creating a walrus ridge",
    "a bamboo forest with shadows forming a koi ridge",
    "a labyrinth with paths creating a key ridge",
    "a coral reef with algae shaping a crown ridge",
    "a night sky with auroras forming a veil ridge",
    "a bridge with reflections creating a mirror ridge",
    "a rose garden with thorns shaping a dagger ridge",
    "a city with rooftops forming a skyline ridge",
    "a chessboard with moves creating a dance ridge",
    "a frozen lake with ice forming a crystal ridge",
    "a festival with lights shaping a sparkler ridge",
    "a desert with rocks forming a monument ridge",
    "a waterfall with mist creating a sprite ridge",
    "a park with trees forming a canopy ridge",
    "a constellation with stars shaping an arrow ridge",
    "a train with steam forming a whistle ridge",
    "a vineyard with leaves creating a wreath ridge",
    "a mountain with ridges forming a falcon ridge",
    "a harbor with waves shaping a siren ridge",
    "a forest with branches forming a lynx ridge",
    "a city with signs creating a billboard ridge",
    "a wheat field with wind shaping a scarecrow ridge",
    "a coral reef with colors forming a palette ridge",
    "a desert with dunes creating a crescent ridge",
    "a library with shelves shaping a ladder ridge",
    "a carnival with rides forming a rollercoaster ridge",
    "a river with ripples creating a mandala ridge",
    "a skyline with lights forming a constellation ridge",
    "a glacier with shadows shaping an iceberg ridge",
    "a bamboo forest with leaves forming a dragonfly ridge",
    "a labyrinth with walls creating a puzzle ridge",
    "a coral reef with fish forming a mosaic ridge",
    "a night sky with stars shaping a galaxy ridge",
    "a bridge with arches forming a rainbow ridge",
    "a rose garden with petals creating a fan ridge",
    "a city with streets forming a circuit ridge",
    "a chessboard with pieces shaping a fortress ridge",
    "a frozen lake with cracks forming a web ridge",
    "a festival with flags creating a parade ridge",
    "a desert with shadows forming a mirage ridge",
    "a waterfall with spray shaping a veil ridge",
    "a park with paths forming a labyrinth ridge",
    "a constellation with stars creating a crown ridge",
    "a train with tracks shaping a horizon ridge",
    "a vineyard with vines forming a lyre ridge",
    "a mountain with peaks shaping a griffin ridge",
    "a harbor with boats forming a fleet ridge",
    "a forest with shadows creating a bear cub ridge",
    "a city with neon forming a heartbeat ridge",
    "a wheat field with stalks shaping a windmill ridge",
    "a coral reef with corals forming a palace ridge",
    "a desert with sand shaping a nomad ridge",
    "a library with books creating a tower ridge",
    "a carnival with tents forming a big top ridge",
    "a river with currents shaping a whirlpool ridge",
    "a skyline with cranes forming a skyline ridge",
    "a glacier with ice shaping a seal pup ridge",
    "a bamboo forest with stalks forming a pagoda ridge",
    "a labyrinth with turns creating a spiral galaxy ridge",
    "a coral reef with waves forming a trident ridge",
    "a night sky with stars shaping a nebula ridge",
    "a bridge with cables forming a web ridge",
    "a rose garden with blooms shaping a scepter ridge",
    "a city with lights forming a symphony ridge",
    "a chessboard with tiles creating a maze ridge",
    "a frozen lake with ice shaping a snow owl ridge",
    "a festival with fireworks forming a starburst ridge",
    "a desert with dunes creating a caravan trail ridge",
    "a waterfall with mist forming a phantom ridge",
    "a park with trees shaping a silhouette ridge",
    "a constellation with stars forming a harp ridge",
    "a train with cars creating a chain ridge",
    "a vineyard with rows forming a scroll ridge",
    "a mountain with cliffs shaping a condor ridge",
    "a harbor with docks forming a compass ridge",
    "a forest with vines creating a panther ridge",
    "a city with billboards shaping a marquee ridge",
    "a wheat field with paths forming a tractor ridge",
    "a coral reef with shells creating a spiral ridge",
    "a desert with mirages forming a mirage city ridge",
    "a library with windows shaping a book ridge",
    "a carnival with flags forming a trapeze ridge",
    "a river with rocks creating a canoe ridge",
    "a skyline with antennas forming a signal ridge",
    "a glacier with ridges shaping a narwhal ridge",
    "a bamboo forest with leaves forming a fan ridge",
    "a labyrinth with paths shaping a keyhole ridge",
    "a coral reef with anemones forming a jellyfish ridge",
    "a night sky with meteors creating a shooting star ridge",
    "a bridge with supports forming a crane ridge",
    "a rose garden with arches shaping a throne ridge",
    "a city with streetlights forming a melody ridge",
    "a chessboard with squares creating a shield ridge",
    "a frozen lake with patterns forming a snowflake ridge",
    "a festival with crowds shaping a stage ridge",
    "a desert with sand forming an hourglass ridge",
    "a waterfall with rainbows creating a prism ridge",
    "a park with shadows forming a carousel ridge",
    "a constellation with lines shaping a chariot ridge",
    "a train with tracks forming a tunnel ridge",
    "a vineyard with grapes creating a chalice ridge",
    "a mountain with snow shaping a yeti ridge",
    "a harbor with buoys forming a compass rose ridge",
    "a forest with leaves creating a stag ridge",
    "a city with bridges shaping a violin ridge",
    "a wheat field with rows forming a plow ridge",
    "a coral reef with fish schools creating a heart ridge",
    "a desert with winds shaping a dervish ridge",
    "a library with book spines forming a globe ridge",
    "a carnival with balloons creating a clown ridge",
    "a river with bends shaping a delta ridge",
    "a skyline with windows forming a code ridge",
    "a glacier with ice creating a walrus ridge",
    "a bamboo forest with shadows forming a koi ridge",
    "a labyrinth with paths creating a key ridge",
    "a coral reef with algae shaping a crown ridge",
    "a night sky with auroras forming a veil ridge",
    "a bridge with reflections creating a mirror ridge",
    "a rose garden with thorns shaping a dagger ridge",
    "a city with rooftops forming a skyline ridge",
    "a chessboard with moves creating a dance ridge",
    "a frozen lake with ice forming a crystal ridge",
    "a festival with lights shaping a sparkler ridge",
    "a desert with rocks forming a monument ridge",
    "a waterfall with mist creating a sprite ridge",
    "a park with trees forming a canopy ridge",
    "a constellation with stars shaping an arrow ridge",
    "a train with steam forming a whistle ridge",
    "a vineyard with leaves creating a wreath ridge",
    "a mountain with ridges forming a falcon ridge",
    "a harbor with waves shaping a siren ridge",
    "a forest with branches forming a lynx ridge",
    "a city with signs creating a billboard ridge",
    "a wheat field with wind shaping a scarecrow ridge",
    "a coral reef with colors forming a palette ridge",
    "a desert with dunes creating a crescent ridge",
    "a library with shelves shaping a ladder ridge",
    "a carnival with rides forming a rollercoaster ridge",
    "a river with ripples creating a mandala ridge",
    "a skyline with lights forming a constellation ridge",
    "a glacier with shadows shaping an iceberg ridge",
    "a bamboo forest with leaves forming a dragonfly ridge",
    "a labyrinth with walls creating a puzzle ridge",
    "a coral reef with fish forming a mosaic ridge",
    "a night sky with stars shaping a galaxy ridge",
    "a bridge with arches forming a rainbow ridge",
    "a rose garden with petals creating a fan ridge",
    "a city with streets forming a circuit ridge",
    "a chessboard with pieces shaping a fortress ridge",
    "a frozen lake with cracks forming a web ridge",
    "a festival with flags creating a parade ridge",
    "a desert with shadows forming a mirage ridge",
    "a waterfall with spray shaping a veil ridge",
    "a park with paths forming a labyrinth ridge",
    "a constellation with stars creating a crown ridge",
    "a train with tracks shaping a horizon ridge",
    "a vineyard with vines forming a lyre ridge",
    "a mountain with peaks shaping a griffin ridge",
    "a harbor with boats forming a fleet ridge",
    "a forest with shadows creating a bear cub ridge",
    "a city with neon forming a heartbeat ridge",
    "a wheat field with stalks shaping a windmill ridge",
    "a coral reef with corals forming a palace ridge",
    "a desert with sand shaping a nomad ridge",
    "a library with books creating a tower ridge",
    "a carnival with tents forming a big top ridge",
    "a river with currents shaping a whirlpool ridge",
    "a skyline with cranes forming a skyline ridge",
    "a glacier with ice shaping a seal pup ridge",
    "a bamboo forest with stalks forming a pagoda ridge",
    "a labyrinth with turns creating a spiral galaxy ridge",
    "a coral reef with waves forming a trident ridge",
    "a night sky with stars shaping a nebula ridge",
    "a bridge with cables forming a web ridge",
    "a rose garden with blooms shaping a scepter ridge",
    "a city with lights forming a symphony ridge",
    "a chessboard with tiles creating a maze ridge",
    "a frozen lake with ice shaping a snow owl ridge",
    "a festival with fireworks forming a starburst ridge",
    "a desert with dunes creating a caravan trail ridge",
    "a waterfall with mist forming a phantom ridge",
    "a park with trees shaping a silhouette ridge",
    "a constellation with stars forming a harp ridge",
    "a train with cars creating a chain ridge",
    "a vineyard with rows forming a scroll ridge",
    "a mountain with cliffs shaping a condor ridge",
    "a harbor with docks forming a compass ridge",
    "a forest with vines creating a panther ridge",
    "a city with billboards shaping a marquee ridge",
    "a wheat field with paths forming a tractor ridge",
    "a coral reef with shells creating a spiral ridge",
    "a desert with mirages forming a mirage city ridge",
    "a library with windows shaping a book ridge",
    "a carnival with flags forming a trapeze ridge",
    "a river with rocks creating a canoe ridge",
    "a skyline with antennas forming a signal ridge",
    "a glacier with ridges shaping a narwhal ridge",
    "a bamboo forest with leaves forming a fan ridge",
    "a labyrinth with paths shaping a keyhole ridge",
    "a coral reef with anemones forming a jellyfish ridge",
    "a night sky with meteors creating a shooting star ridge",
    "a bridge with supports forming a crane ridge",
    "a rose garden with arches shaping a throne ridge",
    "a city with streetlights forming a melody ridge",
    "a chessboard with squares creating a shield ridge",
    "a frozen lake with patterns forming a snowflake ridge",
    "a festival with crowds shaping a stage ridge",
    "a desert with sand forming an hourglass ridge",
    "a waterfall with rainbows creating a prism ridge",
    "a park with shadows forming a carousel ridge",
    "a constellation with lines shaping a chariot ridge",
    "a train with tracks forming a tunnel ridge",
    "a vineyard with grapes creating a chalice ridge",
    "a mountain with snow shaping a yeti ridge",
    "a harbor with buoys forming a compass rose ridge",
    "a forest with leaves creating a stag ridge",
    "a city with bridges shaping a violin ridge",
    "a wheat field with rows forming a plow ridge",
    "a coral reef with fish schools creating a heart ridge",
    "a desert with winds shaping a dervish ridge",
    "a library with book spines forming a globe ridge",
    "a carnival with balloons creating a clown ridge",
    "a river with bends shaping a delta ridge",
    "a skyline with windows forming a code ridge",
    "a glacier with ice creating a walrus ridge",
    "a bamboo forest with shadows forming a koi ridge",
    "a labyrinth with paths creating a key ridge",
    "a coral reef with algae shaping a crown ridge",
    "a night sky with auroras forming a veil ridge",
    "a bridge with reflections creating a mirror ridge",
    "a rose garden with thorns shaping a dagger ridge",
    "a city with rooftops forming a skyline ridge",
    "a chessboard with moves creating a dance ridge",
    "a frozen lake with ice forming a crystal ridge",
    "a festival with lights shaping a sparkler ridge",
    "a desert with rocks forming a monument ridge",
    "a waterfall with mist creating a sprite ridge",
    "a park with trees forming a canopy ridge",
    "a constellation with stars shaping an arrow ridge",
    "a train with steam forming a whistle ridge",
    "a vineyard with leaves creating a wreath ridge",
    "a mountain with ridges forming a falcon ridge",
    "a harbor with waves shaping a siren ridge",
    "a forest with branches forming a lynx ridge",
    "a city with signs creating a billboard ridge",
    "a wheat field with wind shaping a scarecrow ridge",
    "a coral reef with colors forming a palette ridge",
    "a desert with dunes creating a crescent ridge",
    "a library with shelves shaping a ladder ridge",
    "a carnival with rides forming a rollercoaster ridge",
    "a river with ripples creating a mandala ridge",
    "a skyline with lights forming a constellation ridge",
    "a glacier with shadows shaping an iceberg ridge",
    "a bamboo forest with leaves forming a dragonfly ridge",
    "a labyrinth with walls creating a puzzle ridge",
    "a coral reef with fish forming a mosaic ridge",
    "a night sky with stars shaping a galaxy ridge",
    "a bridge with arches forming a rainbow ridge",
    "a rose garden with petals creating a fan ridge",
    "a city with streets forming a circuit ridge",
    "a chessboard with pieces shaping a fortress ridge",
    "a frozen lake with cracks forming a web ridge",
    "a festival with flags creating a parade ridge",
    "a desert with shadows forming a mirage ridge",
    "a waterfall with spray shaping a veil ridge",
    "a park with paths forming a labyrinth ridge",
    "a constellation with stars creating a crown ridge",
    "a train with tracks shaping a horizon ridge",
    "a vineyard with vines forming a lyre ridge",
    "a mountain with peaks shaping a griffin ridge",
    "a harbor with boats forming a fleet ridge",
    "a forest with shadows creating a bear cub ridge",
    "a city with neon forming a heartbeat ridge",
    "a wheat field with stalks shaping a windmill ridge",
    "a coral reef with corals forming a palace ridge",
    "a desert with sand shaping a nomad ridge",
    "a library with books creating a tower ridge",
    "a carnival with tents forming a big top ridge",
    "a river with currents shaping a whirlpool ridge",
    "a skyline with cranes forming a skyline ridge",
    "a glacier with ice shaping a seal pup ridge",
    "a bamboo forest with stalks forming a pagoda ridge",
    "a labyrinth with turns creating a spiral galaxy ridge",
    "a coral reef with waves forming a trident ridge",
    "a night sky with stars shaping a nebula ridge",
    "a bridge with cables forming a web ridge",
    "a rose garden with blooms shaping a scepter ridge",
    "a city with lights forming a symphony ridge",
    "a chessboard with tiles creating a maze ridge",
    "a frozen lake with ice shaping a snow owl ridge",
    "a festival with fireworks forming a starburst ridge",
    "a desert with dunes creating a caravan trail ridge",
    "a waterfall with mist forming a phantom ridge",
    "a park with trees shaping a silhouette ridge",
    "a constellation with stars forming a harp ridge",
    "a train with cars creating a chain ridge",
    "a vineyard with rows forming a scroll ridge",
    "a mountain with cliffs shaping a condor ridge",
    "a harbor with docks forming a compass ridge",
    "a forest with vines creating a panther ridge",
    "a city with billboards shaping a marquee ridge",
    "a wheat field with paths forming a tractor ridge",
    "a coral reef with shells creating a spiral ridge",
    "a desert with mirages forming a mirage city ridge",
    "a library with windows shaping a book ridge",
    "a carnival with flags forming a trapeze ridge",
    "a river with rocks creating a canoe ridge",
    "a skyline with antennas forming a signal ridge",
    "a glacier with ridges shaping a narwhal ridge",
    "a bamboo forest with leaves forming a fan ridge",
    "a labyrinth with paths shaping a keyhole ridge",
    "a coral reef with anemones forming a jellyfish ridge",
    "a night sky with meteors creating a shooting star ridge",
    "a bridge with supports forming a crane ridge",
    "a rose garden with arches shaping a throne ridge",
    "a city with streetlights forming a melody ridge",
    "a chessboard with squares creating a shield ridge",
    "a frozen lake with patterns forming a snowflake ridge",
    "a festival with crowds shaping a stage ridge",
    "a desert with sand forming an hourglass ridge",
    "a waterfall with rainbows creating a prism ridge",
    "a park with shadows forming a carousel ridge",
    "a constellation with lines shaping a chariot ridge",
    "a train with tracks forming a tunnel ridge",
    "a vineyard with grapes creating a chalice ridge",
    "a mountain with snow shaping a yeti ridge",
    "a harbor with buoys forming a compass rose ridge",
    "a forest with leaves creating a stag ridge",
    "a city with bridges shaping a violin ridge",
    "a wheat field with rows forming a plow ridge",
    "a coral reef with fish schools creating a heart ridge",
    "a desert with winds shaping a dervish ridge",
    "a library with book spines forming a globe ridge",
    "a carnival with balloons creating a clown ridge",
    "a river with bends shaping a delta ridge",
    "a skyline with windows forming a code ridge",
    "a glacier with ice creating a walrus ridge",
    "a bamboo forest with shadows forming a koi ridge",
    "a labyrinth with paths creating a key ridge",
    "a coral reef with algae shaping a crown ridge",
    "a night sky with auroras forming a veil ridge",
    "a bridge with reflections creating a mirror ridge",
    "a rose garden with thorns shaping a dagger ridge",
    "a city with rooftops forming a skyline ridge",
    "a chessboard with moves creating a dance ridge",
    "a frozen lake with ice forming a crystal ridge",
    "a festival with lights shaping a sparkler ridge",
    "a desert with rocks forming a monument ridge",
    "a waterfall with mist creating a sprite ridge",
    "a park with trees forming a canopy ridge",
    "a constellation with stars shaping an arrow ridge",
    "a train with steam forming a whistle ridge",
    "a vineyard with leaves creating a wreath ridge",
    "a mountain with ridges forming a falcon ridge",
    "a harbor with waves shaping a siren ridge",
    "a forest with branches forming a lynx ridge",
    "a city with signs creating a billboard ridge",
    "a wheat field with wind shaping a scarecrow ridge",
    "a coral reef with colors forming a palette ridge",
    "a desert with dunes creating a crescent ridge",
    "a library with shelves shaping a ladder ridge",
    "a carnival with rides forming a rollercoaster ridge",
    "a river with ripples creating a mandala ridge",
    "a skyline with lights forming a constellation ridge",
    "a glacier with shadows shaping an iceberg ridge",
    "a bamboo forest with leaves forming a dragonfly ridge",
    "a labyrinth with walls creating a puzzle ridge",
    "a coral reef with fish forming a mosaic ridge",
    "a night sky with stars shaping a galaxy ridge",
    "a bridge with arches forming a rainbow ridge",
    "a rose garden with petals creating a fan ridge",
    "a city with streets forming a circuit ridge",
    "a chessboard with pieces shaping a fortress ridge",
    "a frozen lake with cracks forming a web ridge",
    "a festival with flags creating a parade ridge",
    "a desert with shadows forming a mirage ridge",
    "a waterfall with spray shaping a veil ridge",
    "a park with paths forming a labyrinth ridge",
    "a constellation with stars creating a crown ridge",
    "a train with tracks shaping a horizon ridge",
    "a vineyard with vines forming a lyre ridge",
    "a mountain with peaks shaping a griffin ridge",
    "a harbor with boats forming a fleet ridge",
    "a forest with shadows creating a bear cub ridge",
    "a city with neon forming a heartbeat ridge",
    "a wheat field with stalks shaping a windmill ridge",
    "a coral reef with corals forming a palace ridge",
    "a desert with sand shaping a nomad ridge",
    "a library with books creating a tower ridge",
    "a carnival with tents forming a big top ridge",
    "a river with currents shaping a whirlpool ridge",
    "a skyline with cranes forming a skyline ridge",
    "a glacier with ice shaping a seal pup ridge",
    "a bamboo forest with stalks forming a pagoda ridge",
    "a labyrinth with turns creating a spiral galaxy ridge",
    "a coral reef with waves forming a trident ridge",
    "a night sky with stars shaping a nebula ridge",
    "a bridge with cables forming a web ridge",
    "a rose garden with blooms shaping a scepter ridge",
    "a city with lights forming a symphony ridge",
    "a chessboard with tiles creating a maze ridge",
    "a frozen lake with ice shaping a snow owl ridge",
    "a festival with fireworks forming a starburst ridge",
    "a desert with dunes creating a caravan trail ridge",
    "a waterfall with mist forming a phantom ridge",
    "a park with trees shaping a silhouette ridge",
    "a constellation with stars forming a harp ridge",
    "a train with cars creating a chain ridge",
    "a vineyard with rows forming a scroll ridge",
    "a mountain with cliffs shaping a condor ridge",
    "a harbor with docks forming a compass ridge",
    "a forest with vines creating a panther ridge",
    "a city with billboards shaping a marquee ridge",
    "a wheat field with paths forming a tractor ridge",
    "a coral reef with shells creating a spiral ridge",
    "a desert with mirages forming a mirage city ridge",
    "a library with windows shaping a book ridge",
    "a carnival with flags forming a trapeze ridge",
    "a river with rocks creating a canoe ridge",
    "a skyline with antennas forming a signal ridge",
    "a glacier with ridges shaping a narwhal ridge",
    "a bamboo forest with leaves forming a fan ridge",
    "a labyrinth with paths shaping a keyhole ridge",
    "a coral reef with anemones forming a jellyfish ridge",
    "a night sky with meteors creating a shooting star ridge",
    "a bridge with supports forming a crane ridge",
    "a rose garden with arches shaping a throne ridge",
    "a city with streetlights forming a melody ridge",
    "a chessboard with squares creating a shield ridge",
    "a frozen lake with patterns forming a snowflake ridge",
    "a festival with crowds shaping a stage ridge",
    "a desert with sand forming an hourglass ridge"
];

function getPrompt() {
    const illusion = illusions[generationIndex % illusions.length];
    return `Create a 9:16 vertical optical illusion image where ${illusion}. Use high-contrast neon colors, a layered clean structure, and maximalist but clear composition that requires viewers to pause to notice the illusion, not too obvious at first glance. Add cinematic particle effects, neon glow, and glitch details for virality. **Compulsorily include the text at the top in bold yellow with a thin black outline: \"What do you see first?\"** integrated seamlessly without blocking the illusion.`;
}

function pastePromptAutom(promptText) {
    const sel = ['div.ql-editor.textarea.new-input-ui', 'div[contenteditable="true"]', 'textarea', '[role="textbox"]', 'div[contenteditable]', '.ProseMirror'];
    const input = sel.map(s => document.querySelector(s)).find(Boolean);
    if (!input) {
        console.error("Input not found");
        return false;
    }
    input.textContent = promptText;
    ['input', 'change', 'keyup', 'paste'].forEach(e => input.dispatchEvent(new Event(e, { bubbles: true, cancelable: true })));
    input.focus();
    input.dispatchEvent(new FocusEvent('focus', { bubbles: true }));
    return true;
}

function submitPrompt() {
    if (generationIndex >= totalGenerations) {
        return console.log("✅ All 400 illusion image prompts generated!");
    }
    const prompt = getPrompt();
    if (!pastePromptAutom(prompt)) {
        return setTimeout(submitPrompt, retryDelay);
    }
    setTimeout(() => {
        const btn = ['button.send-button', 'button[aria-label="Send"]', 'button[type="submit"]', '[data-testid="send-button"]'].map(s => document.querySelector(s)).find(Boolean);
        if (btn && !btn.disabled) btn.click();
        generationIndex++;
        setTimeout(submitPrompt, delay);
    }, 3000);
}

console.log("🚀 Starting 400 unique illusion image automation with CTA overlay...");
submitPrompt();
