let generationIndex = 0,
    delay = 30000,
    totalGenerations = 400,
    retryDelay = 5000;

const memes = [
    "a cat with laser eyes riding a skateboard on a rainbow road",
    "a buff doge lifting weights while crying",
    "a frog with sunglasses holding a coffee cup in a post-apocalyptic wasteland",
    "a giga chad riding a dolphin through a neon city",
    "a skeleton wearing a crown sitting on a throne of memes",
    "a sad wojak staring at a computer with flames in the background",
    "a monkey in a suit holding a briefcase running late",
    "a penguin with a jetpack flying over a cyberpunk city",
    "a raccoon stealing pizza slices under neon lights",
    "a potato with sunglasses sitting on a golden throne",
    "a shiba inu in a tuxedo DJing at a rave",
    "a toaster with googly eyes sprinting through a glitchy void",
    "a dancing baby yoda in a VR headset on a floating platform",
    "a screaming alpaca in a cowboy hat riding a meteor",
    "a sentient energy drink can leading a cult in a neon desert",
    "a wojak in a tracksuit flexing in front of a crashing stock market",
    "a pepe the frog as a hacker in a dystopian server room",
    "a flaming hot cheeto with arms vibing in a lava lamp world",
    "a dinosaur in a bucket hat selling NFTs on the moon",
    "a cursed emoji leading an army of emojis in a pixelated war",
    "a dancing hot dog in a tuxedo at a glitchy prom",
    "a sentient fidget spinner orbiting a neon black hole",
    "a crying wojak in a clown wig selling crypto at a loss",
    "a taco with wings soaring through a vaporwave sky",
    "a pepe in a spacesuit mining bitcoin on an asteroid",
    "a screaming goat in sunglasses driving a cybertruck",
    "a sentient vape pen leading a riot in a glitchy mall",
    "a doge in a wizard robe casting spells in a pixel forest",
    "a sad pepe eating ramen in a neon-lit alley",
    "a dancing banana in a tracksuit at a Skibidi Toilet convention",
    "a chad hamster in a tiny sports car racing through Ohio",
    "a flaming skull DJing at a rave in a digital void",
    "a wojak in a bucket hat staring at a glitching NFT",
    "a sentient pizza slice breakdancing on a holographic stage",
    "a frog in a mech suit battling a giant Ohio boss",
    "a doge in a chef hat cooking cursed ramen in a neon kitchen",
    "a pepe as a cyberpunk samurai slicing through a glitch storm",
    "a sentient AirPod leading a rebellion in a dystopian ear",
    "a crying cat in a hoodie scrolling TikTok at 3 AM",
    "a chad goldfish in sunglasses swimming in a lava lamp ocean",
    "a wojak in a VR headset lost in a Skibidi multiverse",
    "a dancing pickle in a tuxedo at a neon wedding",
    "a pepe in a bomber jacket flying a drone over a cyber city",
    "a sentient meme coin mooning in a glitchy stock market",
    "a doge in a crown ruling a kingdom of flaming emojis",
    "a sad wojak in a tracksuit stuck in a 404 error page",
    "a frog with a jetpack dodging lasers in a neon maze",
    "a chad raccoon stealing NFTs in a digital heist",
    "a dancing skeleton in a bucket hat vibing in a pixel graveyard",
    "a pepe in a spacesuit vibing on a neon comet",
    "a sentient energy drink can preaching in a glitchy church",
    "a crying doge in a hoodie staring at a crashing crypto chart",
    "a frog in a tuxedo hosting a chaotic meme awards show",
    "a chad alpaca in sunglasses spitting bars in a neon studio",
    "a dancing toaster in a tracksuit at a glitchy rave",
    "a pepe in a cowboy hat riding a robotic bull in Ohio",
    "a sentient Takis bag leading a revolution in a neon desert",
    "a sad wojak in a VR headset lost in a Skibidi simulation",
    "a doge in a chef hat grilling burgers in a cyberpunk food truck",
    "a frog in a bomber jacket flying a jet over a pixel city",
    "a chad cat with laser eyes hacking a neon mainframe",
    "a dancing emoji in a crown ruling a glitchy kingdom",
    "a pepe in a tracksuit dodging meteors in a vaporwave void",
    "a sentient pizza box DJing at a neon pizza party",
    "a crying wojak in sunglasses staring at a glitching phone",
    "a doge in a wizard hat casting spells in a digital forest",
    "a frog in a spacesuit exploring a neon alien planet",
    "a chad hamster in a tiny crown ruling a pixel empire",
    "a dancing banana in a hoodie vibing in a Skibidi Toilet arena",
    "a pepe in a mech suit battling a giant glitch monster",
    "a sentient vape cloud forming a face in a neon sky",
    "a sad doge in a bucket hat scrolling Reddit in a cyber alley",
    "a frog in a tuxedo hosting a cursed meme game show",
    "a chad raccoon in sunglasses stealing crypto in a digital vault",
    "a dancing skeleton in a tracksuit vibing in a neon cemetery",
    "a pepe in a bomber jacket flying a drone in a glitch storm",
    "a sentient energy drink can preaching in a pixel cathedral",
    "a crying cat in a VR headset lost in a Skibidi multiverse",
    "a doge in a crown ruling a kingdom of flaming memes",
    "a frog in a spacesuit dodging lasers on a neon asteroid",
    "a chad alpaca in a bucket hat spitting bars in a digital studio",
    "a dancing toaster in sunglasses at a glitchy festival",
    "a pepe in a cowboy hat riding a robotic horse in Ohio",
    "a sentient Takis bag leading a riot in a neon city",
    "a sad wojak in a hoodie staring at a crashing NFT market",
    "a doge in a chef hat cooking cursed tacos in a cyber kitchen",
    "a frog in a bomber jacket flying a jet in a pixel sky",
    "a chad cat with laser eyes hacking a glitchy server",
    "a dancing emoji in a crown ruling a neon empire",
    "a pepe in a tracksuit dodging meteors in a digital void",
    "a sentient pizza box DJing at a glitchy rave",
    "a crying wojak in sunglasses staring at a glitching TikTok",
    "a doge in a wizard hat casting spells in a neon forest",
    "a frog in a spacesuit exploring a pixel alien world",
    "a chad hamster in a tiny crown ruling a glitchy kingdom",
    "a dancing banana in a hoodie vibing in a Skibidi arena",
    "a pepe in a mech suit battling a giant Ohio monster",
    "a sentient vape cloud forming a face in a pixel sky",
    "a sad doge in a bucket hat scrolling X in a cyber alley",
    "a frog in a tuxedo hosting a cursed meme awards",
    "a chad raccoon in sunglasses stealing NFTs in a neon vault",
    "a dancing skeleton in a tracksuit vibing in a pixel graveyard",
    "a pepe in a bomber jacket flying a drone in a neon storm",
    "a sentient energy drink can preaching in a glitchy temple",
    "a crying cat in a VR headset lost in a Skibidi simulation",
    "a doge in a crown ruling a kingdom of cursed emojis",
    "a frog in a spacesuit dodging lasers in a digital asteroid field",
    "a chad alpaca in a bucket hat spitting bars in a neon studio",
    "a dancing toaster in sunglasses at a pixel festival",
    "a pepe in a cowboy hat riding a robotic bull in a glitchy Ohio",
    "a sentient Takis bag leading a revolution in a digital desert",
    "a sad wojak in a hoodie staring at a crashing crypto market",
    "a doge in a chef hat grilling cursed burgers in a neon food truck",
    "a frog in a bomber jacket flying a jet in a glitchy sky",
    "a chad cat with laser eyes hacking a pixel mainframe",
    "a dancing emoji in a crown ruling a glitchy empire",
    "a pepe in a tracksuit dodging meteors in a neon void",
    "a sentient pizza box DJing at a pixel pizza party",
    "a crying wojak in sunglasses staring at a glitching phone screen",
    "a doge in a wizard hat casting spells in a digital jungle",
    "a frog in a spacesuit exploring a neon alien wasteland",
    "a chad hamster in a tiny crown ruling a pixel kingdom",
    "a dancing banana in a hoodie vibing in a Skibidi Toilet stadium",
    "a pepe in a mech suit battling a giant glitch boss",
    "a sentient vape cloud forming a skull in a neon sky",
    "a sad doge in a bucket hat scrolling TikTok in a cyber alley",
    "a frog in a tuxedo hosting a chaotic meme game show",
    "a chad raccoon in sunglasses stealing crypto in a glitchy vault",
    "a dancing skeleton in a tracksuit vibing in a neon necropolis",
    "a pepe in a bomber jacket flying a drone in a pixel storm",
    "a sentient energy drink can preaching in a digital cathedral",
    "a crying cat in a VR headset lost in a Skibidi multiverse",
    "a doge in a crown ruling a kingdom of flaming GIFs",
    "a frog in a spacesuit dodging lasers in a neon asteroid belt",
    "a chad alpaca in a bucket hat spitting bars in a pixel studio",
    "a dancing toaster in sunglasses at a glitchy carnival",
    "a pepe in a cowboy hat riding a robotic horse in a digital Ohio",
    "a sentient Takis bag leading a riot in a neon wasteland",
    "a sad wojak in a hoodie staring at a crashing meme coin chart",
    "a doge in a chef hat cooking cursed ramen in a cyber kitchen",
    "a frog in a bomber jacket flying a jet in a pixelated sky",
    "a chad cat with laser eyes hacking a neon server room",
    "a dancing emoji in a crown ruling a digital empire",
    "a pepe in a tracksuit dodging meteors in a glitchy void",
    "a sentient pizza box DJing at a neon rave",
    "a crying wojak in sunglasses staring at a glitching X post",
    "a doge in a wizard hat casting spells in a pixel jungle",
    "a frog in a spacesuit exploring a digital alien planet",
    "a chad hamster in a tiny crown ruling a neon kingdom",
    "a dancing banana in a hoodie vibing in a Skibidi Toilet arena",
    "a pepe in a mech suit battling a giant Ohio boss",
    "a sentient vape cloud forming a face in a pixel sky",
    "a sad doge in a bucket hat scrolling Reddit in a neon alley",
    "a frog in a tuxedo hosting a cursed meme awards show",
    "a chad raccoon in sunglasses stealing NFTs in a digital heist",
    "a dancing skeleton in a tracksuit vibing in a glitchy graveyard",
    "a pepe in a bomber jacket flying a drone in a neon storm",
    "a sentient energy drink can preaching in a pixel temple",
    "a crying cat in a VR headset lost in a Skibidi simulation",
    "a doge in a crown ruling a kingdom of cursed memes",
    "a frog in a spacesuit dodging lasers in a digital asteroid field",
    "a chad alpaca in a bucket hat spitting bars in a neon studio",
    "a dancing toaster in sunglasses at a pixel rave",
    "a pepe in a cowboy hat riding a robotic bull in a glitchy Ohio",
    "a sentient Takis bag leading a revolution in a digital city",
    "a sad wojak in a hoodie staring at a crashing crypto chart",
    "a doge in a chef hat grilling cursed tacos in a neon food truck",
    "a frog in a bomber jacket flying a jet in a glitchy sky",
    "a chad cat with laser eyes hacking a pixel mainframe",
    "a dancing emoji in a crown ruling a neon empire",
    "a pepe in a tracksuit dodging meteors in a digital void",
    "a sentient pizza box DJing at a glitchy pizza party",
    "a crying wojak in sunglasses staring at a glitching TikTok feed",
    "a doge in a wizard hat casting spells in a neon jungle",
    "a frog in a spacesuit exploring a pixel alien wasteland",
    "a chad hamster in a tiny crown ruling a glitchy empire",
    "a dancing banana in a hoodie vibing in a Skibidi Toilet stadium",
    "a pepe in a mech suit battling a giant glitch monster",
    "a sentient vape cloud forming a skull in a digital sky",
    "a sad doge in a bucket hat scrolling X in a cyber alley",
];

const brainrotLines = [
    "SKIBIDI TOILET LIVING RENT FREE IN MY BRAIN 🧠💦",
    "OHIO FINAL BOSS VIBES ONLY 🚫🧢",
    "MY LAST 2 BRAIN CELLS FIGHTING FOR 3RD PLACE 😭",
    "CAUGHT ME ACTING UNWISE AT 3AM 💀",
    "LIVING IN A SIMULATION BUT I’M LAGGING 📡",
    "RIZZLER ENERGY ONLY NO OHIO VANS 🚐",
    "POV: YOU ATE THE LAST TAKIS AND FEEL NO GUILT 🔥",
    "GYATT ALGORITHM HITTING DIFFERENT FR 🍑",
    "BRAINROT CERTIFIED, NO CURE IN SIGHT 🦠",
    "SKIBIDI BIDEN BLAST GOT ME UNINSTALLED 😩",
    "MEWING STREAK: 0 DAYS, JAWLINE GONE 📉",
    "ZOOMER BRAIN ON DIAL-UP SPEED 🐢",
    "GRIMACE SHAKE HIT ME LIKE A TRUCK 🚚💜",
    "LIVING FOR THE PLOT TWIST IN OHIO 🌀",
    "SIGMA GRINDSET BUT I’M ON AUX 😤",
    "FORTNITE LOBBY MENTALITY IN REAL LIFE 🦙",
    "BRAINROT PB&J SANDWICH NO CRUST 🥪",
    "SCROLLING TIKTOK TILL MY EYES UN渲染 😵",
    "OHIO WIFI GOT ME ON 1 BAR OF SANITY 📶",
    "RIZZ WOLF HOWLING AT A PIXEL MOON 🌑",
    "SKIBIDI DOP DOP YES YES NO BRAIN 🧠🚽",
    "MY VIBES ON ANOTHER ASTRAL PLANE ✈️",
    "GIGACHAD MINDSET, WII SPORTS SKILLS 🎾",
    "CAUGHT LACKING IN THE ALGORITHM 😱",
    "BRAINROT DIET: TAKIS AND MOUNTAIN DEW 🥤",
    "SIGMA HUSTLE BUT MY PC CRASHED 💻💥",
    "OHIO DEMON SPAWNED IN MY DMS 😈",
    "MEWING THROUGH THE PAIN OF EXISTENCE 😬",
    "GYATT DETECTOR OFF THE CHARTS 📊",
    "SKIBIDI TOILET ARC ALTERED MY DNA 🧬",
    "ZOOMER LORE DROPPING AT 4AM 📜",
    "RIZZLER VIBES BUT NO ONE MATCHES MY FREAK 😔",
    "BRAINROT SPEEDRUN ANY% NO SKIPS 🏃‍♂️",
    "OHIO SUNSET HITTING LIKE A JUMPSCARE 🌅",
    "SIGMA GRIND BUT MY BRAIN ON FLAPPY BIRD 🐦",
    "GRIMACE SHAKE ERASED MY MEMORY CARD 🟣",
    "LIVING IN SKIBIDI MULTIVERSE MADNESS 🌌",
    "MY LAST BRAIN CELL ON LIFE SUPPORT 🩺",
    "RIZZLER AURA BUT I’M MUTED IN VC 🔇",
    "OHIO PORTAL OPENED IN MY BACKYARD 🚪",
    "BRAINROT CERTIFICATE FRAMED ON MY WALL 🖼️",
    "MEWING TILL I ASCEND TO THE SKIBIDI PLANE 🙏",
    "GYATT ECONOMY IN SHAMBLES 📉",
    "ZOOMER BRAIN ON 144P RESOLUTION 📺",
    "SIGMA HUSTLE BUT I’M STUCK IN TUTORIAL 🕹️",
    "OHIO AIR SMELLS LIKE TAKIS FUEGO 🌬️",
    "SKIBIDI TOILET LORE RUNNING MY LIFE 🎥",
    "RIZZ WOLF BUT MY PACK IS NPCS 🐺",
    "BRAINROT VIRUS FULLY INSTALLED 🦠",
    "GRIMACE SHAKE GOT ME IN WITHDRAWAL 😵‍💫",
    "MEWING THROUGH A 5G CONSPIRACY 📡",
    "GYATT QUEST UNLOCKED BUT NO XP GAINED 🏆",
    "OHIO FINAL BOSS SPAWNED IN MY DREAMS 😴",
    "SIGMA MINDSET BUT I’M ON 2 FPS 🖥️",
    "SKIBIDI TOILET CANON ALTERED MY TIMELINE ⏳",
    "RIZZLER VIBES BUT I’M BANNED FROM OHIO 🚫",
    "BRAINROT LORE DEEPER THAN THE DARK WEB 🕸️",
    "ZOOMER AURA BUT MY WIFI IS DIAL-UP 📞",
    "GRIMACE SHAKE TASTES LIKE REGRET 💧",
    "MEWING TILL I UNLOCK GOD MODE 😎",
    "GYATT SINGULARITY COLLAPSING MY BRAIN 🕳️",
    "OHIO SKIES RAINING SKIBIDI TOILETS 🌧️",
    "SIGMA GRIND BUT MY BRAIN IS LAGGING 🐌",
    "BRAINROT ARC HITTING LIKE A TRUCK 🚛",
    "RIZZ WOLF BUT MY HOWL IS AUTO-TUNED 🎙️",
    "SKIBIDI TOILET DROPPED NEW LORE AT 3AM 📖",
    "ZOOMER VIBES BUT MY BRAIN IS BUFFering 🌀",
    "OHIO QUESTLINE GOT ME ON HARD MODE 🎮",
    "GRIMACE SHAKE WIPED MY SAVE FILE 😭",
    "MEWING TILL MY JAWLINE CUTS DIAMONDS 💎",
    "GYATT RADAR PINGING OFF THE CHARTS 📡",
    "SIGMA HUSTLE BUT MY BRAIN IS ON 1HP ❤️",
    "BRAINROT LORE HITTING LIKE A METEOR ☄️",
    "RIZZ WOLF BUT MY PACK IS LAGGING 🐺",
    "SKIBIDI TOILET MOVIE DROPPING 2026 🎬",
    "ZOOMER AURA BUT MY BRAIN IS ON MUTE 🔇",
    "OHIO PORTAL SPAWNED IN MY BASEMENT 🚪",
    "GRIMACE SHAKE GOT ME SEEING PIXELS 👾",
    "MEWING TILL MY JAWLINE BREAKS PHYSICS ⚡",
    "GYATT SINGULARITY EATING MY BRAIN CELLS 🕳️",
    "SIGMA HUSTLE BUT MY VIBES ARE OFFLINE 📴",
    "BRAINROT VIRUS REWRITING MY CODE 🧬",
    "OHIO SKIES DROPPING SKIBIDI METEORS ☄️",
    "RIZZLER VIBES BUT MY AURA IS GLITCHED 🖥️",
    "SKIBIDI TOILET LORE BURNED MY RETINAS 👀",
    "ZOOMER BRAIN ON 2G NETWORK SPEED 📡",
    "GRIMACE SHAKE TASTES LIKE ETERNAL DOOM 💜",
    "MEWING TILL I ASCEND TO OHIO HEAVEN 😇",
    "GYATT QUEST CRASHED MY MENTAL SERVER 🖥️",
    "OHIO FINAL BOSS LIVING IN MY HEAD RENT FREE 😈",
    "SIGMA HUSTLE BUT MY BRAIN IS ON 1HP ❤️",
    "BRAINROT LORE HITTING LIKE A METEOR ☄️",
    "RIZZ WOLF BUT MY PACK IS LAGGING 🐺",
    "SKIBIDI TOILET MOVIE DROPPING 2026 🎬",
    "ZOOMER AURA BUT MY BRAIN IS ON MUTE 🔇",
    "OHIO PORTAL SPAWNED IN MY BASEMENT 🚪",
    "GRIMACE SHAKE GOT ME SEEING PIXELS 👾",
    "MEWING TILL MY JAWLINE BREAKS PHYSICS ⚡",
    "GYATT SINGULARITY EATING MY BRAIN CELLS 🕳️",
    "SIGMA HUSTLE BUT MY VIBES ARE OFFLINE 📴",
    "BRAINROT VIRUS REWRITING MY CODE 🧬",
];

function getPrompt() {
    const meme = memes[generationIndex % memes.length];
    const brainrot = brainrotLines[generationIndex % brainrotLines.length];
    return `Create a 9:16 vertical brainrot meme image depicting ${meme}. Use hyper-vivid, high-exposure neon colors with a chaotic, maximalist composition typical of brainrot memes. Add glitch, sparkles, and viral particle effects. **Compulsorily and permanently include the following BRAINROT TEXT in large, bold yellow with thin black outline at the top: "${brainrot}" — do not skip or alter this text under any circumstances; it must be included clearly in the image design.** Make it absurd, humorous, and instantly scroll-stopping.`;
}

function pastePromptAutom(promptText) {
    const sel = ['div.ql-editor.textarea.new-input-ui', 'div[contenteditable="true"]', 'textarea', '[role="textbox"]', 'div[contenteditable]', '.ProseMirror'];
    const input = sel.map(s => document.querySelector(s)).find(Boolean);
    if (!input) {
        console.error("Input not found");
        return false;
    }
    input.textContent = promptText;
    ['input', 'change', 'keyup', 'paste'].forEach(e => input.dispatchEvent(new Event(e, { bubbles: true, cancelable: true })));
    input.focus();
    input.dispatchEvent(new FocusEvent('focus', { bubbles: true }));
    return true;
}

function submitPrompt() {
    if (generationIndex >= totalGenerations) {
        return console.log("✅ All 400 brainrot meme prompts with permanent overlay generated!");
    }
    const prompt = getPrompt();
    if (!pastePromptAutom(prompt)) {
        return setTimeout(submitPrompt, retryDelay);
    }
    setTimeout(() => {
        const btn = ['button.send-button', 'button[aria-label="Send"]', 'button[type="submit"]', '[data-testid="send-button"]'].map(s => document.querySelector(s)).find(Boolean);
        if (btn && !btn.disabled) btn.click();
        generationIndex++;
        setTimeout(submitPrompt, delay);
    }, 3000);
}

console.log("🚀 Starting 400 brainrot meme automation with compulsory permanent BRAINROT TEXT overlay...");
submitPrompt();