import os
import pickle
import random
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

# Load credentials
with open("token_ai_models.pickle", "rb") as token_file:
    creds = pickle.load(token_file)

youtube = build("youtube", "v3", credentials=creds)

BASE_DIR = os.path.dirname(__file__)
VIDEO_DIR = os.path.join(BASE_DIR, "Youtube", "Res")
INDEX_FILE = os.path.join(BASE_DIR, "ai_models_last_index.txt")

# Get next video
files = sorted(
    [f for f in os.listdir(VIDEO_DIR) if f.endswith(".mp4")],
    key=lambda x: int(''.join(filter(str.isdigit, x)) or 0)
)
total = len(files)
index = 0
if os.path.exists(INDEX_FILE):
    with open(INDEX_FILE, "r") as f:
        index = int(f.read().strip())
next_video = files[index % total]
with open(INDEX_FILE, "w") as f:
    f.write(str((index + 1) % total))

video_path = os.path.join(VIDEO_DIR, next_video)
base_name = os.path.splitext(next_video)[0]

# Dynamic unique title generation
titles = [
    "Breathtaking AI Models You've Never Seen",
    "Next-Level AI Fashion Generated by Bing",
    "Stunning Virtual Models for Your Inspiration",
    "Gorgeous AI-Generated Models To Blow Your Mind",
    "Unreal AI Models Created with Bing Sora",
    "Mesmerizing AI Fashion Concepts",
    "Hyper-Realistic AI Model Showcase",
    "Unbelievable AI Model Transformations",
    "AI Fashion Week: Stunning Looks",
    "Virtual Runway: Gorgeous AI Models",
    "Aesthetic AI Models You Will Love",
    "Stylish AI Creations for Your Feed",
    "Next-Gen AI Models to Follow Now",
    "Incredible AI Model Renderings",
    "Hyper-Real AI Looks Created with Bing",
    "Insane AI Model Shots with Stunning Details",
    "Trending AI Models Captured in HD",
    "AI Model Showcase: Virtual Beauties",
    "Captivating AI Model Styles",
    "Explore Stunning AI Models",
    "Beautiful AI Models Rendered Perfectly",
    "Viral AI Model Content to Inspire",
    "Mind-Blowing AI Models by Bing Sora",
    "Elegant AI Model Showcase",
    "Glamorous AI Model Concepts You Need to See",
    "Futuristic AI Fashion Models",
    "Must-See AI Model Aesthetics",
    "AI Model Shots for Your Inspiration",
    "Unique AI-Generated Model Styles",
    "Immaculate AI Model Fashion Shots"
]

title = f"{random.choice(titles)} | AI Models #{base_name}"

# Long SEO-optimized description
description = f"""
{title}

Experience the world of hyper-realistic, stunning AI-generated models, crafted using Bing Sora to deliver the best in AI aesthetics, virtual fashion, and digital creativity. Each video showcases unreal transformations and styles created with advanced AI tools, curated for your inspiration and creativity.

These AI models were generated by Bing through the Sora model pipeline, ensuring unique and eye-catching visuals to elevate your content feed. Whether you're a creator seeking new ideas, a fashion enthusiast, or someone fascinated by the future of AI artistry, these videos will captivate your imagination.

✨ Credits:
- Videos generated using Bing through the Sora AI model.
- Music synced for a seamless Shorts experience.

📌 Tags:
#AImodels #VirtualModels #FashionAI #Shorts #Bing #Sora #AestheticAI #AIArt #FutureOfFashion #AIShorts #Trending

Subscribe for more AI-powered visual inspirations and stunning content!
"""

# Upload
request_body = {
    "snippet": {
        "title": title,
        "description": description.strip(),
        "tags": [
            "AI models", "Virtual models", "AI fashion", "AI art",
            "Bing Sora", "Shorts", "Trending", "Future fashion",
            "Aesthetic AI", "Hyper realistic models"
        ],
        "categoryId": "22"
    },
    "status": {
        "privacyStatus": "public"
    }
}

media = MediaFileUpload(video_path, mimetype="video/mp4", resumable=True)
request = youtube.videos().insert(part="snippet,status", body=request_body, media_body=media)
response = request.execute()

print(f"✅ Upload successful: https://youtube.com/watch?v={response['id']}")
