name: Auto Upload Motivational Shorts

on:
  schedule:
    - cron: '30 19 * * *'  # Runs daily at 1:00 AM IST (19:30 UTC)
  workflow_dispatch:        # Enables "Run workflow" button for manual testing

jobs:
  upload_motivational:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Decode Client Secret
        run: |
          echo "${{ secrets.MOTIVATIONAL_SECRET }}" | base64 -d > client_motivational_quotes.json

      - name: Decode OAuth Token
        run: |
          echo "${{ secrets.MOTIVATIONAL_PICKLE }}" | base64 -d > token_motivational.pickle

      - name: Upload Motivational Video
        run: |
          python local_upload_test_motivational.py

      - name: Configure Git for pushing updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit updated index file
        run: |
          git add current_index_motivational.txt
          git commit -m "Update current index for next motivational upload" || echo "No changes to commit"

      - name: Push updated index to repository
        run: |
          git push
